name: pipeline

on:
  push:
    branches:
      - main

jobs:
  echo_branch:
    runs-on: ubuntu-latest
    
    steps:       
      - name: First pipe
        run: "echo Branch: main"
  
  test:
    runs-on: ubuntu-latest

    steps:
      - name: unit test
        run: "npm run test"