name: First Workflow

on:
  push:
    branches:
      - main

jobs:
  echo_branch:
    runs-on: ubuntu-latest

    steps:
      - name: First step
        run: 'echo Branch: main'

  check_unit_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Installs Packets
        run: 'npm i'

      - name: Runs Unit Test
        run: 'npm run test'

      - name: Runs eslint
        run: 'npm run lint'